/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyAttendanceRouteImport } from './routes/my-attendance'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppMyAttendanceRouteImport } from './routes/app.my-attendance'
import { Route as AppAttendanceIndexRouteImport } from './routes/app.attendance.index'
import { Route as AppAttendanceAttendanceIdRouteImport } from './routes/app.attendance.$attendanceId'
import { Route as AppInventoryIndexRouteImport } from './routes/app.inventory.index'
import { Route as AppInventoryAdjustmentsRouteImport } from './routes/app.inventory.adjustments'
import { Route as AppInventoryConsumptionRouteImport } from './routes/app.inventory.consumption'
import { Route as AppInventoryPurchasesRouteImport } from './routes/app.inventory.purchases'
import { Route as AppInventorySuppliersRouteImport } from './routes/app.inventory.suppliers'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard.employees.index'
import { Route as DashboardEmployeesEmployeeIdRouteImport } from './routes/dashboard.employees.$employeeId'
import { Route as DashboardEmployeesNewRouteImport } from './routes/dashboard.employees.new'
import { Route as AppInventoryProductsIndexRouteImport } from './routes/app.inventory.products.index'
import { Route as AppInventoryProductsProductIdRouteImport } from './routes/app.inventory.products.$productId'
import { Route as DashboardEmployeesEmployeeIdIndexRouteImport } from './routes/dashboard.employees.$employeeId.index'
import { Route as DashboardEmployeesEmployeeIdActivityRouteImport } from './routes/dashboard.employees.$employeeId.activity'
import { Route as DashboardEmployeesEmployeeIdAttendanceRouteImport } from './routes/dashboard.employees.$employeeId.attendance'
import { Route as DashboardEmployeesEmployeeIdEditRouteImport } from './routes/dashboard.employees.$employeeId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAttendanceRoute = MyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyAttendanceRoute = AppMyAttendanceRouteImport.update({
  id: '/app/my-attendance',
  path: '/app/my-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/app/attendance/',
  path: '/app/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttendanceAttendanceIdRoute =
  AppAttendanceAttendanceIdRouteImport.update({
    id: '/app/attendance/$attendanceId',
    path: '/app/attendance/$attendanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/app/inventory/',
  path: '/app/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryAdjustmentsRoute = AppInventoryAdjustmentsRouteImport.update({
  id: '/app/inventory/adjustments',
  path: '/app/inventory/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryConsumptionRoute = AppInventoryConsumptionRouteImport.update({
  id: '/app/inventory/consumption',
  path: '/app/inventory/consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryPurchasesRoute = AppInventoryPurchasesRouteImport.update({
  id: '/app/inventory/purchases',
  path: '/app/inventory/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventorySuppliersRoute = AppInventorySuppliersRouteImport.update({
  id: '/app/inventory/suppliers',
  path: '/app/inventory/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesEmployeeIdRoute =
  DashboardEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployeesNewRoute = DashboardEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => DashboardRoute,
} as any)
const AppInventoryProductsIndexRoute =
  AppInventoryProductsIndexRouteImport.update({
    id: '/app/inventory/products/',
    path: '/app/inventory/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppInventoryProductsProductIdRoute =
  AppInventoryProductsProductIdRouteImport.update({
    id: '/app/inventory/products/$productId',
    path: '/app/inventory/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardEmployeesEmployeeIdIndexRoute =
  DashboardEmployeesEmployeeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEmployeesEmployeeIdRoute,
  } as any)
const DashboardEmployeesEmployeeIdActivityRoute =
  DashboardEmployeesEmployeeIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardEmployeesEmployeeIdRoute,
  } as any)
const DashboardEmployeesEmployeeIdAttendanceRoute =
  DashboardEmployeesEmployeeIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardEmployeesEmployeeIdRoute,
  } as any)
const DashboardEmployeesEmployeeIdEditRoute =
  DashboardEmployeesEmployeeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardEmployeesEmployeeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/my-attendance': typeof MyAttendanceRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/app/my-attendance': typeof AppMyAttendanceRoute
  '/app/attendance/$attendanceId': typeof AppAttendanceAttendanceIdRoute
  '/app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/app/inventory/consumption': typeof AppInventoryConsumptionRoute
  '/app/inventory/purchases': typeof AppInventoryPurchasesRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRouteWithChildren
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/app/attendance/': typeof AppAttendanceIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/app/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/dashboard/employees/$employeeId/activity': typeof DashboardEmployeesEmployeeIdActivityRoute
  '/dashboard/employees/$employeeId/attendance': typeof DashboardEmployeesEmployeeIdAttendanceRoute
  '/dashboard/employees/$employeeId/edit': typeof DashboardEmployeesEmployeeIdEditRoute
  '/app/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/dashboard/employees/$employeeId/': typeof DashboardEmployeesEmployeeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/my-attendance': typeof MyAttendanceRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/app/my-attendance': typeof AppMyAttendanceRoute
  '/app/attendance/$attendanceId': typeof AppAttendanceAttendanceIdRoute
  '/app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/app/inventory/consumption': typeof AppInventoryConsumptionRoute
  '/app/inventory/purchases': typeof AppInventoryPurchasesRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/app/attendance': typeof AppAttendanceIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/app/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/dashboard/employees/$employeeId/activity': typeof DashboardEmployeesEmployeeIdActivityRoute
  '/dashboard/employees/$employeeId/attendance': typeof DashboardEmployeesEmployeeIdAttendanceRoute
  '/dashboard/employees/$employeeId/edit': typeof DashboardEmployeesEmployeeIdEditRoute
  '/app/inventory/products': typeof AppInventoryProductsIndexRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/appointments': typeof AppointmentsRoute
  '/attendance': typeof AttendanceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/my-attendance': typeof MyAttendanceRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/app/my-attendance': typeof AppMyAttendanceRoute
  '/app/attendance/$attendanceId': typeof AppAttendanceAttendanceIdRoute
  '/app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/app/inventory/consumption': typeof AppInventoryConsumptionRoute
  '/app/inventory/purchases': typeof AppInventoryPurchasesRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRouteWithChildren
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/app/attendance/': typeof AppAttendanceIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/app/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/dashboard/employees/$employeeId/activity': typeof DashboardEmployeesEmployeeIdActivityRoute
  '/dashboard/employees/$employeeId/attendance': typeof DashboardEmployeesEmployeeIdAttendanceRoute
  '/dashboard/employees/$employeeId/edit': typeof DashboardEmployeesEmployeeIdEditRoute
  '/app/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/dashboard/employees/$employeeId/': typeof DashboardEmployeesEmployeeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/appointments'
    | '/attendance'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/my-attendance'
    | '/notifications'
    | '/payroll'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/app/my-attendance'
    | '/app/attendance/$attendanceId'
    | '/app/inventory/adjustments'
    | '/app/inventory/consumption'
    | '/app/inventory/purchases'
    | '/app/inventory/suppliers'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/app/attendance/'
    | '/app/inventory/'
    | '/dashboard/employees/'
    | '/app/inventory/products/$productId'
    | '/dashboard/employees/$employeeId/activity'
    | '/dashboard/employees/$employeeId/attendance'
    | '/dashboard/employees/$employeeId/edit'
    | '/app/inventory/products/'
    | '/dashboard/employees/$employeeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/appointments'
    | '/attendance'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/my-attendance'
    | '/notifications'
    | '/payroll'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/app/my-attendance'
    | '/app/attendance/$attendanceId'
    | '/app/inventory/adjustments'
    | '/app/inventory/consumption'
    | '/app/inventory/purchases'
    | '/app/inventory/suppliers'
    | '/dashboard/employees/new'
    | '/app/attendance'
    | '/app/inventory'
    | '/dashboard/employees'
    | '/app/inventory/products/$productId'
    | '/dashboard/employees/$employeeId/activity'
    | '/dashboard/employees/$employeeId/attendance'
    | '/dashboard/employees/$employeeId/edit'
    | '/app/inventory/products'
    | '/dashboard/employees/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/appointments'
    | '/attendance'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/my-attendance'
    | '/notifications'
    | '/payroll'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/app/my-attendance'
    | '/app/attendance/$attendanceId'
    | '/app/inventory/adjustments'
    | '/app/inventory/consumption'
    | '/app/inventory/purchases'
    | '/app/inventory/suppliers'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/app/attendance/'
    | '/app/inventory/'
    | '/dashboard/employees/'
    | '/app/inventory/products/$productId'
    | '/dashboard/employees/$employeeId/activity'
    | '/dashboard/employees/$employeeId/attendance'
    | '/dashboard/employees/$employeeId/edit'
    | '/app/inventory/products/'
    | '/dashboard/employees/$employeeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeesRoute: typeof EmployeesRoute
  FinanceRoute: typeof FinanceRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MyAttendanceRoute: typeof MyAttendanceRoute
  NotificationsRoute: typeof NotificationsRoute
  PayrollRoute: typeof PayrollRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  AppMyAttendanceRoute: typeof AppMyAttendanceRoute
  AppAttendanceAttendanceIdRoute: typeof AppAttendanceAttendanceIdRoute
  AppInventoryAdjustmentsRoute: typeof AppInventoryAdjustmentsRoute
  AppInventoryConsumptionRoute: typeof AppInventoryConsumptionRoute
  AppInventoryPurchasesRoute: typeof AppInventoryPurchasesRoute
  AppInventorySuppliersRoute: typeof AppInventorySuppliersRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInventoryProductsProductIdRoute: typeof AppInventoryProductsProductIdRoute
  AppInventoryProductsIndexRoute: typeof AppInventoryProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-attendance': {
      id: '/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof MyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/my-attendance': {
      id: '/app/my-attendance'
      path: '/app/my-attendance'
      fullPath: '/app/my-attendance'
      preLoaderRoute: typeof AppMyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/attendance/': {
      id: '/app/attendance/'
      path: '/app/attendance'
      fullPath: '/app/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/attendance/$attendanceId': {
      id: '/app/attendance/$attendanceId'
      path: '/app/attendance/$attendanceId'
      fullPath: '/app/attendance/$attendanceId'
      preLoaderRoute: typeof AppAttendanceAttendanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/app/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory/adjustments': {
      id: '/app/inventory/adjustments'
      path: '/app/inventory/adjustments'
      fullPath: '/app/inventory/adjustments'
      preLoaderRoute: typeof AppInventoryAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory/consumption': {
      id: '/app/inventory/consumption'
      path: '/app/inventory/consumption'
      fullPath: '/app/inventory/consumption'
      preLoaderRoute: typeof AppInventoryConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory/purchases': {
      id: '/app/inventory/purchases'
      path: '/app/inventory/purchases'
      fullPath: '/app/inventory/purchases'
      preLoaderRoute: typeof AppInventoryPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory/suppliers': {
      id: '/app/inventory/suppliers'
      path: '/app/inventory/suppliers'
      fullPath: '/app/inventory/suppliers'
      preLoaderRoute: typeof AppInventorySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/employees'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/$employeeId': {
      id: '/dashboard/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/dashboard/employees/$employeeId'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/new': {
      id: '/dashboard/employees/new'
      path: '/employees/new'
      fullPath: '/dashboard/employees/new'
      preLoaderRoute: typeof DashboardEmployeesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/app/inventory/products/': {
      id: '/app/inventory/products/'
      path: '/app/inventory/products'
      fullPath: '/app/inventory/products/'
      preLoaderRoute: typeof AppInventoryProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory/products/$productId': {
      id: '/app/inventory/products/$productId'
      path: '/app/inventory/products/$productId'
      fullPath: '/app/inventory/products/$productId'
      preLoaderRoute: typeof AppInventoryProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employees/$employeeId/': {
      id: '/dashboard/employees/$employeeId/'
      path: '/'
      fullPath: '/dashboard/employees/$employeeId/'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof DashboardEmployeesEmployeeIdRoute
    }
    '/dashboard/employees/$employeeId/activity': {
      id: '/dashboard/employees/$employeeId/activity'
      path: '/activity'
      fullPath: '/dashboard/employees/$employeeId/activity'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdActivityRouteImport
      parentRoute: typeof DashboardEmployeesEmployeeIdRoute
    }
    '/dashboard/employees/$employeeId/attendance': {
      id: '/dashboard/employees/$employeeId/attendance'
      path: '/attendance'
      fullPath: '/dashboard/employees/$employeeId/attendance'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdAttendanceRouteImport
      parentRoute: typeof DashboardEmployeesEmployeeIdRoute
    }
    '/dashboard/employees/$employeeId/edit': {
      id: '/dashboard/employees/$employeeId/edit'
      path: '/edit'
      fullPath: '/dashboard/employees/$employeeId/edit'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof DashboardEmployeesEmployeeIdRoute
    }
  }
}

interface DashboardEmployeesEmployeeIdRouteChildren {
  DashboardEmployeesEmployeeIdActivityRoute: typeof DashboardEmployeesEmployeeIdActivityRoute
  DashboardEmployeesEmployeeIdAttendanceRoute: typeof DashboardEmployeesEmployeeIdAttendanceRoute
  DashboardEmployeesEmployeeIdEditRoute: typeof DashboardEmployeesEmployeeIdEditRoute
  DashboardEmployeesEmployeeIdIndexRoute: typeof DashboardEmployeesEmployeeIdIndexRoute
}

const DashboardEmployeesEmployeeIdRouteChildren: DashboardEmployeesEmployeeIdRouteChildren =
  {
    DashboardEmployeesEmployeeIdActivityRoute:
      DashboardEmployeesEmployeeIdActivityRoute,
    DashboardEmployeesEmployeeIdAttendanceRoute:
      DashboardEmployeesEmployeeIdAttendanceRoute,
    DashboardEmployeesEmployeeIdEditRoute:
      DashboardEmployeesEmployeeIdEditRoute,
    DashboardEmployeesEmployeeIdIndexRoute:
      DashboardEmployeesEmployeeIdIndexRoute,
  }

const DashboardEmployeesEmployeeIdRouteWithChildren =
  DashboardEmployeesEmployeeIdRoute._addFileChildren(
    DashboardEmployeesEmployeeIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardEmployeesEmployeeIdRoute: typeof DashboardEmployeesEmployeeIdRouteWithChildren
  DashboardEmployeesNewRoute: typeof DashboardEmployeesNewRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEmployeesEmployeeIdRoute:
    DashboardEmployeesEmployeeIdRouteWithChildren,
  DashboardEmployeesNewRoute: DashboardEmployeesNewRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppointmentsRoute: AppointmentsRoute,
  AttendanceRoute: AttendanceRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeesRoute: EmployeesRoute,
  FinanceRoute: FinanceRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MyAttendanceRoute: MyAttendanceRoute,
  NotificationsRoute: NotificationsRoute,
  PayrollRoute: PayrollRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  AppMyAttendanceRoute: AppMyAttendanceRoute,
  AppAttendanceAttendanceIdRoute: AppAttendanceAttendanceIdRoute,
  AppInventoryAdjustmentsRoute: AppInventoryAdjustmentsRoute,
  AppInventoryConsumptionRoute: AppInventoryConsumptionRoute,
  AppInventoryPurchasesRoute: AppInventoryPurchasesRoute,
  AppInventorySuppliersRoute: AppInventorySuppliersRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInventoryProductsProductIdRoute: AppInventoryProductsProductIdRoute,
  AppInventoryProductsIndexRoute: AppInventoryProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
