// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID        string
	Message   string
	Type      string
	User      string
	ServerID  sql.NullString
	CreatedAt time.Time
}

type MonitoringSnapshot struct {
	ID          string
	ServerID    string
	CpuUsage    float64
	MemoryUsage float64
	DiskUsage   float64
	NetworkIn   float64
	NetworkOut  float64
	CreatedAt   time.Time
}

type Notification struct {
	ID        string
	Title     string
	Message   string
	Type      string
	Read      bool
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Server struct {
	ID            string
	Name          string
	Ip            string
	Os            string
	Status        string
	CpuUsage      float64
	MemoryUsage   float64
	MemoryTotal   float64
	DiskUsage     float64
	DiskTotal     float64
	NetworkIn     float64
	NetworkOut    float64
	Uptime        int64
	Location      string
	Provider      string
	Tags          string
	SshPort       int32
	SshUser       string
	SshAuthMethod string
	SshPassword   string
	SshPrivateKey string
	SshPassphrase string
	HostKey       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
