// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createActivity = `-- name: CreateActivity :exec
INSERT INTO activities (id, message, type, "user", server_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateActivityParams struct {
	ID        string
	Message   string
	Type      string
	User      string
	ServerID  sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.ExecContext(ctx, createActivity,
		arg.ID,
		arg.Message,
		arg.Type,
		arg.User,
		arg.ServerID,
		arg.CreatedAt,
	)
	return err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, title, message, type, read, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateNotificationParams struct {
	ID        string
	Title     string
	Message   string
	Type      string
	Read      bool
	CreatedAt time.Time
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.Title,
		arg.Message,
		arg.Type,
		arg.Read,
		arg.CreatedAt,
	)
	return err
}

const createServer = `-- name: CreateServer :exec
INSERT INTO servers (
	id, name, ip, os, status, cpu_usage, memory_usage, memory_total,
	disk_usage, disk_total, network_in, network_out, uptime, location,
	provider, tags, ssh_port, ssh_user, ssh_auth_method, ssh_password,
	ssh_private_key, ssh_passphrase, host_key, created_at, updated_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25
)
`

type CreateServerParams struct {
	ID            string
	Name          string
	Ip            string
	Os            string
	Status        string
	CpuUsage      float64
	MemoryUsage   float64
	MemoryTotal   float64
	DiskUsage     float64
	DiskTotal     float64
	NetworkIn     float64
	NetworkOut    float64
	Uptime        int64
	Location      string
	Provider      string
	Tags          string
	SshPort       int32
	SshUser       string
	SshAuthMethod string
	SshPassword   string
	SshPrivateKey string
	SshPassphrase string
	HostKey       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.ExecContext(ctx, createServer,
		arg.ID,
		arg.Name,
		arg.Ip,
		arg.Os,
		arg.Status,
		arg.CpuUsage,
		arg.MemoryUsage,
		arg.MemoryTotal,
		arg.DiskUsage,
		arg.DiskTotal,
		arg.NetworkIn,
		arg.NetworkOut,
		arg.Uptime,
		arg.Location,
		arg.Provider,
		arg.Tags,
		arg.SshPort,
		arg.SshUser,
		arg.SshAuthMethod,
		arg.SshPassword,
		arg.SshPrivateKey,
		arg.SshPassphrase,
		arg.HostKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO refresh_tokens (id, user_id, token, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers
WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteServer, id)
	return err
}

const deleteServersBulk = `-- name: DeleteServersBulk :exec
DELETE FROM servers
WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteServersBulk(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.ExecContext(ctx, deleteServersBulk, pq.Array(dollar_1))
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteToken, token)
	return err
}

const deleteTokensByUserID = `-- name: DeleteTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByUserID, userID)
	return err
}

const getActivities = `-- name: GetActivities :many
SELECT id, message, type, "user", server_id, created_at
FROM activities
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetActivities(ctx context.Context, limit int32) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, getActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.Type,
			&i.User,
			&i.ServerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllServers = `-- name: GetAllServers :many
SELECT 
	id, name, ip, os, status, cpu_usage, memory_usage, memory_total,
	disk_usage, disk_total, network_in, network_out, uptime, location,
	provider, tags, ssh_port, ssh_user, ssh_auth_method, ssh_password,
	ssh_private_key, ssh_passphrase, host_key, created_at, updated_at
FROM servers
ORDER BY created_at DESC
`

func (q *Queries) GetAllServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, getAllServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.Os,
			&i.Status,
			&i.CpuUsage,
			&i.MemoryUsage,
			&i.MemoryTotal,
			&i.DiskUsage,
			&i.DiskTotal,
			&i.NetworkIn,
			&i.NetworkOut,
			&i.Uptime,
			&i.Location,
			&i.Provider,
			&i.Tags,
			&i.SshPort,
			&i.SshUser,
			&i.SshAuthMethod,
			&i.SshPassword,
			&i.SshPrivateKey,
			&i.SshPassphrase,
			&i.HostKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotifications = `-- name: GetNotifications :many
SELECT id, title, message, type, read, created_at
FROM notifications
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) GetNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerByID = `-- name: GetServerByID :one
SELECT 
	id, name, ip, os, status, cpu_usage, memory_usage, memory_total,
	disk_usage, disk_total, network_in, network_out, uptime, location,
	provider, tags, ssh_port, ssh_user, ssh_auth_method, ssh_password,
	ssh_private_key, ssh_passphrase, host_key, created_at, updated_at
FROM servers
WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id string) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Os,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.MemoryTotal,
		&i.DiskUsage,
		&i.DiskTotal,
		&i.NetworkIn,
		&i.NetworkOut,
		&i.Uptime,
		&i.Location,
		&i.Provider,
		&i.Tags,
		&i.SshPort,
		&i.SshUser,
		&i.SshAuthMethod,
		&i.SshPassword,
		&i.SshPrivateKey,
		&i.SshPassphrase,
		&i.HostKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSnapshotsByServer = `-- name: GetSnapshotsByServer :many
SELECT id, server_id, cpu_usage, memory_usage, disk_usage, network_in, network_out, created_at
FROM monitoring_snapshots
WHERE server_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetSnapshotsByServerParams struct {
	ServerID string
	Limit    int32
}

func (q *Queries) GetSnapshotsByServer(ctx context.Context, arg GetSnapshotsByServerParams) ([]MonitoringSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getSnapshotsByServer, arg.ServerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonitoringSnapshot
	for rows.Next() {
		var i MonitoringSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.CpuUsage,
			&i.MemoryUsage,
			&i.DiskUsage,
			&i.NetworkIn,
			&i.NetworkOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshotsSince = `-- name: GetSnapshotsSince :many
SELECT cpu_usage, memory_usage, network_in, network_out, created_at
FROM monitoring_snapshots
WHERE created_at >= $1
ORDER BY created_at ASC
`

type GetSnapshotsSinceRow struct {
	CpuUsage    float64
	MemoryUsage float64
	NetworkIn   float64
	NetworkOut  float64
	CreatedAt   time.Time
}

func (q *Queries) GetSnapshotsSince(ctx context.Context, createdAt time.Time) ([]GetSnapshotsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, getSnapshotsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSnapshotsSinceRow
	for rows.Next() {
		var i GetSnapshotsSinceRow
		if err := rows.Scan(
			&i.CpuUsage,
			&i.MemoryUsage,
			&i.NetworkIn,
			&i.NetworkOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToken = `-- name: GetToken :one
SELECT user_id, id, expires_at
FROM refresh_tokens
WHERE token = $1
`

type GetTokenRow struct {
	UserID    string
	ID        string
	ExpiresAt time.Time
}

func (q *Queries) GetToken(ctx context.Context, token string) (GetTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getToken, token)
	var i GetTokenRow
	err := row.Scan(&i.UserID, &i.ID, &i.ExpiresAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO monitoring_snapshots (
	id, server_id, cpu_usage, memory_usage, disk_usage, network_in, network_out, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSnapshotParams struct {
	ID          string
	ServerID    string
	CpuUsage    float64
	MemoryUsage float64
	DiskUsage   float64
	NetworkIn   float64
	NetworkOut  float64
	CreatedAt   time.Time
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshot,
		arg.ID,
		arg.ServerID,
		arg.CpuUsage,
		arg.MemoryUsage,
		arg.DiskUsage,
		arg.NetworkIn,
		arg.NetworkOut,
		arg.CreatedAt,
	)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications
SET read = TRUE
WHERE read = FALSE
`

func (q *Queries) MarkNotificationsRead(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markNotificationsRead)
	return err
}

const updateServerHostKey = `-- name: UpdateServerHostKey :exec
UPDATE servers
SET host_key = $1, updated_at = $2
WHERE id = $3
`

type UpdateServerHostKeyParams struct {
	HostKey   string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateServerHostKey(ctx context.Context, arg UpdateServerHostKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateServerHostKey, arg.HostKey, arg.UpdatedAt, arg.ID)
	return err
}

const updateServerMetrics = `-- name: UpdateServerMetrics :exec
UPDATE servers
SET 
	status = $1, cpu_usage = $2, memory_usage = $3, memory_total = $4,
	disk_usage = $5, disk_total = $6, network_in = $7, network_out = $8,
	uptime = $9, os = $10, updated_at = $11
WHERE id = $12
`

type UpdateServerMetricsParams struct {
	Status      string
	CpuUsage    float64
	MemoryUsage float64
	MemoryTotal float64
	DiskUsage   float64
	DiskTotal   float64
	NetworkIn   float64
	NetworkOut  float64
	Uptime      int64
	Os          string
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateServerMetrics(ctx context.Context, arg UpdateServerMetricsParams) error {
	_, err := q.db.ExecContext(ctx, updateServerMetrics,
		arg.Status,
		arg.CpuUsage,
		arg.MemoryUsage,
		arg.MemoryTotal,
		arg.DiskUsage,
		arg.DiskTotal,
		arg.NetworkIn,
		arg.NetworkOut,
		arg.Uptime,
		arg.Os,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
