/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard.employees.index'
import { Route as DashboardEmployeesEmployeeIdRouteImport } from './routes/dashboard.employees.$employeeId'
import { Route as DashboardEmployeesNewRouteImport } from './routes/dashboard.employees.new'
import { Route as DashboardEmployeesEmployeeIdIndexRouteImport } from './routes/dashboard.employees.$employeeId.index'
import { Route as DashboardEmployeesEmployeeIdAttendanceRouteImport } from './routes/dashboard.employees.$employeeId.attendance'
import { Route as DashboardEmployeesEmployeeIdEditRouteImport } from './routes/dashboard.employees.$employeeId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesEmployeeIdRoute =
  DashboardEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployeesNewRoute = DashboardEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesEmployeeIdIndexRoute =
  DashboardEmployeesEmployeeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEmployeesEmployeeIdRoute,
  } as any)
const DashboardEmployeesEmployeeIdAttendanceRoute =
  DashboardEmployeesEmployeeIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardEmployeesEmployeeIdRoute,
  } as any)
const DashboardEmployeesEmployeeIdEditRoute =
  DashboardEmployeesEmployeeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardEmployeesEmployeeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/appointments': typeof AppointmentsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRouteWithChildren
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/employees/$employeeId/attendance': typeof DashboardEmployeesEmployeeIdAttendanceRoute
  '/dashboard/employees/$employeeId/edit': typeof DashboardEmployeesEmployeeIdEditRoute
  '/dashboard/employees/$employeeId/': typeof DashboardEmployeesEmployeeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/appointments': typeof AppointmentsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/employees/$employeeId/attendance': typeof DashboardEmployeesEmployeeIdAttendanceRoute
  '/dashboard/employees/$employeeId/edit': typeof DashboardEmployeesEmployeeIdEditRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/appointments': typeof AppointmentsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRouteWithChildren
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/employees/$employeeId/attendance': typeof DashboardEmployeesEmployeeIdAttendanceRoute
  '/dashboard/employees/$employeeId/edit': typeof DashboardEmployeesEmployeeIdEditRoute
  '/dashboard/employees/$employeeId/': typeof DashboardEmployeesEmployeeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/appointments'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/login'
    | '/products'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/employees/'
    | '/dashboard/employees/$employeeId/attendance'
    | '/dashboard/employees/$employeeId/edit'
    | '/dashboard/employees/$employeeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/appointments'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/login'
    | '/products'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/dashboard/employees/new'
    | '/dashboard/employees'
    | '/dashboard/employees/$employeeId/attendance'
    | '/dashboard/employees/$employeeId/edit'
    | '/dashboard/employees/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/appointments'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/login'
    | '/products'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/employees/'
    | '/dashboard/employees/$employeeId/attendance'
    | '/dashboard/employees/$employeeId/edit'
    | '/dashboard/employees/$employeeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeesRoute: typeof EmployeesRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/employees'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/$employeeId': {
      id: '/dashboard/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/dashboard/employees/$employeeId'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/new': {
      id: '/dashboard/employees/new'
      path: '/employees/new'
      fullPath: '/dashboard/employees/new'
      preLoaderRoute: typeof DashboardEmployeesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/$employeeId/': {
      id: '/dashboard/employees/$employeeId/'
      path: '/'
      fullPath: '/dashboard/employees/$employeeId/'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof DashboardEmployeesEmployeeIdRoute
    }
    '/dashboard/employees/$employeeId/attendance': {
      id: '/dashboard/employees/$employeeId/attendance'
      path: '/attendance'
      fullPath: '/dashboard/employees/$employeeId/attendance'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdAttendanceRouteImport
      parentRoute: typeof DashboardEmployeesEmployeeIdRoute
    }
    '/dashboard/employees/$employeeId/edit': {
      id: '/dashboard/employees/$employeeId/edit'
      path: '/edit'
      fullPath: '/dashboard/employees/$employeeId/edit'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof DashboardEmployeesEmployeeIdRoute
    }
  }
}

interface DashboardEmployeesEmployeeIdRouteChildren {
  DashboardEmployeesEmployeeIdAttendanceRoute: typeof DashboardEmployeesEmployeeIdAttendanceRoute
  DashboardEmployeesEmployeeIdEditRoute: typeof DashboardEmployeesEmployeeIdEditRoute
  DashboardEmployeesEmployeeIdIndexRoute: typeof DashboardEmployeesEmployeeIdIndexRoute
}

const DashboardEmployeesEmployeeIdRouteChildren: DashboardEmployeesEmployeeIdRouteChildren =
  {
    DashboardEmployeesEmployeeIdAttendanceRoute:
      DashboardEmployeesEmployeeIdAttendanceRoute,
    DashboardEmployeesEmployeeIdEditRoute:
      DashboardEmployeesEmployeeIdEditRoute,
    DashboardEmployeesEmployeeIdIndexRoute:
      DashboardEmployeesEmployeeIdIndexRoute,
  }

const DashboardEmployeesEmployeeIdRouteWithChildren =
  DashboardEmployeesEmployeeIdRoute._addFileChildren(
    DashboardEmployeesEmployeeIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardEmployeesEmployeeIdRoute: typeof DashboardEmployeesEmployeeIdRouteWithChildren
  DashboardEmployeesNewRoute: typeof DashboardEmployeesNewRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEmployeesEmployeeIdRoute:
    DashboardEmployeesEmployeeIdRouteWithChildren,
  DashboardEmployeesNewRoute: DashboardEmployeesNewRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppointmentsRoute: AppointmentsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeesRoute: EmployeesRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
