/**
 * The TypeScript artifact contracts are checked against responses the backend
 * actually produced.
 *
 * `session-api.json` is generated by `backend/scripts/emit_session_fixture.py`,
 * which writes a real patch and a real evaluated timeline through the same
 * service calls the agent loop uses. Checking the contracts against real output
 * means a field the backend drops, renames, or retypes surfaces here instead of
 * as a blank panel.
 */

import { describe, it, expect, expectTypeOf } from "vitest";
import rawFixture from "./fixtures/session-api.json";
import {
  decodeCrossSessionEventList,
  decodePatch,
  decodeTimeline,
  FixtureDecodeError,
} from "./fixtures/decode-session-fixture";
import {
  BisectCommitRead,
  BisectOutcome,
  SessionEventListResponse,
  SessionPatchRead,
  SessionTimelineRead,
} from "../lib/api/types";

const fixture = rawFixture as unknown;

const patch: SessionPatchRead = decodePatch(
  (fixture as Record<string, unknown>).patch
);
const timeline: SessionTimelineRead = decodeTimeline(
  (fixture as Record<string, unknown>).timeline
);
const crossSessionEvents: SessionEventListResponse = decodeCrossSessionEventList(
  (fixture as Record<string, unknown>).cross_session_event_list
);

describe("patch contract decodes a real backend response", () => {
  it("decodes the fields the review panel reads", () => {
    expect(patch.session_id).toBeTruthy();
    expect(patch.exists).toBe(true);
    expect(patch.is_empty).toBe(false);
    expect(patch.diff).toContain("diff --git");
  });

  it("carries the diff verbatim rather than a pre-parsed shape", () => {
    // The backend stores one opaque blob, so the panel parses it. A pre-parsed
    // `files` array here would mean the contract had drifted to a shape the API
    // does not actually return.
    expect(patch).toHaveProperty("diff");
    expect(patch).not.toHaveProperty("files");
  });

  it("preserves a secret-looking string that redaction would have removed", () => {
    expect(JSON.stringify(rawFixture)).not.toMatch(/ghp_[A-Za-z0-9]{20,}/);
  });
});

describe("timeline contract decodes a real backend response", () => {
  it("decodes commits in the backend-assigned evaluation order", () => {
    expect(timeline.session_id).toBe(patch.session_id);
    expect(timeline.exists).toBe(true);
    expect(timeline.commits.length).toBeGreaterThan(1);
  });

  it("marks exactly one commit as the proven culprit", () => {
    const culprits = timeline.commits.filter(
      (commit) => commit.outcome === "culprit"
    );
    expect(culprits.length).toBe(1);
    expect(culprits[0].hash).toBe(timeline.culprit_hash);
  });

  it("distinguishes a proven culprit from a commit that merely tested bad", () => {
    const outcomes = new Set(timeline.commits.map((commit) => commit.outcome));
    expect(outcomes).toContain("bad");
    expect(outcomes).toContain("culprit");
    expect(outcomes).toContain("good");
  });

  it("carries the fields the scrubber renders", () => {
    for (const field of [
      "hash",
      "short_hash",
      "message",
      "author",
      "timestamp",
      "outcome",
      "test_output",
      "duration_seconds",
    ]) {
      expect(Object.keys(timeline.commits[0])).toContain(field);
    }
  });
});

describe("cross-session event contract decodes a real backend response", () => {
  it("spans more than one session, each event naming its own", () => {
    expect(new Set(crossSessionEvents.items.map((i) => i.session_id)).size)
      .toBeGreaterThan(1);
  });

  it("reports no resumable cursor for a combined feed", () => {
    // `sequence` is a per-session counter, so a single number cannot order or
    // resume a combined feed. Null is honest; a number would not be.
    expect(crossSessionEvents.last_sequence).toBeNull();
  });

  it("returns events oldest first, the order a feed displays them in", () => {
    const stamps = crossSessionEvents.items.map((item) => item.created_at);
    expect(stamps).toEqual([...stamps].sort());
  });
});

describe("the artifact decoders reject a drifted backend payload", () => {
  it("rejects a patch missing a required field", () => {
    const withoutIsEmpty: Record<string, unknown> = { ...patch };
    delete withoutIsEmpty.is_empty;
    expect(() => decodePatch(withoutIsEmpty)).toThrow(FixtureDecodeError);
  });

  it("rejects a wrongly typed exists flag", () => {
    expect(() => decodePatch({ ...patch, exists: "yes" })).toThrow(
      /expected a boolean/
    );
  });

  it("rejects a bisect outcome outside the closed set", () => {
    const drifted = {
      ...timeline,
      commits: [{ ...timeline.commits[0], outcome: "suspect" }],
    };
    expect(() => decodeTimeline(drifted)).toThrow(
      /expected one of good \| bad \| culprit/
    );
  });

  it("rejects a timeline whose commits are not an array", () => {
    expect(() => decodeTimeline({ ...timeline, commits: {} })).toThrow(
      /expected an array/
    );
  });

  it("rejects a wrongly typed duration", () => {
    const drifted = {
      ...timeline,
      commits: [{ ...timeline.commits[0], duration_seconds: "fast" }],
    };
    expect(() => decodeTimeline(drifted)).toThrow(/expected a number/);
  });
});

describe("type-level guarantees, enforced by tsc --noEmit", () => {
  type HasStringIndexSignature<T> = string extends keyof T ? true : false;
  type IsAny<T> = 0 extends 1 & T ? true : false;

  it("admits no arbitrary keys on the artifact contracts", () => {
    // An index signature here would let a panel read a key the backend never
    // sends and get `undefined` instead of a compile error.
    expectTypeOf<HasStringIndexSignature<SessionPatchRead>>().toEqualTypeOf<false>();
    expectTypeOf<HasStringIndexSignature<SessionTimelineRead>>().toEqualTypeOf<false>();
    expectTypeOf<HasStringIndexSignature<BisectCommitRead>>().toEqualTypeOf<false>();
  });

  it("rejects reading a key the backend never sends", () => {
    const read = patch;
    // @ts-expect-error the patch response carries no files array, so reading one must not compile
    expect(read.files).toBeUndefined();

    const commit = timeline.commits[0];
    // @ts-expect-error the backend reports an outcome, not a bare verdict
    expect(commit.verdict).toBeUndefined();
  });

  it("types no artifact contract as any", () => {
    expectTypeOf<IsAny<SessionPatchRead>>().toEqualTypeOf<false>();
    expectTypeOf<IsAny<SessionTimelineRead>>().toEqualTypeOf<false>();
    expectTypeOf<IsAny<BisectCommitRead>>().toEqualTypeOf<false>();
    expectTypeOf<IsAny<BisectOutcome>>().toEqualTypeOf<false>();
  });

  it("rejects a bisect outcome outside the closed set", () => {
    // @ts-expect-error "suspect" is not a BisectOutcome
    const wrong: BisectOutcome = "suspect";
    expect(["good", "bad", "culprit"]).not.toContain(wrong);
  });
});
