/**
 * The TypeScript session contracts are checked against a response the backend
 * actually produced.
 *
 * `session-api.json` is generated by `backend/scripts/emit_session_fixture.py`,
 * which builds real `SessionRead` / `SessionListResponse` /
 * `SessionEventListResponse` objects and serializes them. Checking the contracts
 * against real output means a field the backend drops, renames, or retypes shows
 * up here instead of as a blank panel in the UI.
 *
 * A JSON import widens `"running"` to `string`, so the fixture is decoded through
 * `decode-session-fixture.ts` rather than assigned directly. That makes the check
 * work in both directions: the decoders' return types force the contracts to
 * accept what the backend sent, and a decoder that throws forces them to keep
 * matching.
 */

import { describe, it, expect, expectTypeOf } from "vitest";
import rawFixture from "./fixtures/session-api.json";
import {
  decodeEventList,
  decodeSession,
  decodeSessionList,
  FixtureDecodeError,
} from "./fixtures/decode-session-fixture";
import {
  AgentSession,
  SESSION_EVENT_CATEGORIES,
  SessionEvent,
  SessionEventCategory,
  SessionEventPayload,
  SessionListResponse,
} from "../lib/api/types";

const fixture = rawFixture as unknown;

const session: AgentSession = decodeSession((fixture as Record<string, unknown>).session);
const sessionList: SessionListResponse = decodeSessionList(
  (fixture as Record<string, unknown>).session_list
);
const eventList = decodeEventList(
  (fixture as Record<string, unknown>).event_list
);

describe("session contracts decode a real backend response", () => {
  it("decodes a session", () => {
    expect(session.id).toBeTruthy();
    expect(session.owner_id).toBeTruthy();
    expect("repository_id" in session).toBe(true);
  });

  it("decodes a session list whose length matches its total", () => {
    expect(sessionList.items.length).toBe(sessionList.total);
    expect(sessionList.limit).toBeGreaterThan(0);
    expect(sessionList.offset).toBe(0);
  });

  it("decodes an event list ending at last_sequence", () => {
    expect(eventList.items.length).toBeGreaterThan(0);
    expect(eventList.after_sequence).toBe(0);
    expect(eventList.last_sequence).toBe(
      eventList.items[eventList.items.length - 1].sequence
    );
  });

  it("assigns every captured event a category from the closed set", () => {
    for (const event of eventList.items) {
      expect(SESSION_EVENT_CATEGORIES).toContain(event.category);
    }
  });

  it("captures both a running and a terminal session", () => {
    const statuses = sessionList.items.map((item) => item.status);
    expect(statuses).toContain("running");
    expect(statuses).toContain("completed");
  });

  it("carries the fields the UI reads", () => {
    for (const field of [
      "id",
      "owner_id",
      "repository_id",
      "task_prompt",
      "status",
      "iteration_count",
      "executed_action_count",
      "created_at",
      "started_at",
      "completed_at",
      "termination_reason",
      "prompt_tokens",
      "completion_tokens",
      "total_tokens",
      "steps",
    ]) {
      expect(Object.keys(session)).toContain(field);
    }
  });

  it("shows redaction reaching the serialized payload", () => {
    // The backend redacts before serializing, so a raw token surviving into the
    // fixture would mean redaction was bypassed somewhere.
    expect(JSON.stringify(rawFixture)).not.toMatch(/ghp_[A-Za-z0-9]{20,}/);
    expect(JSON.stringify(rawFixture)).not.toMatch(/sk-ant-[A-Za-z0-9-]{20,}/);
  });
});

describe("the decoders reject a drifted backend payload", () => {
  it("rejects a session missing a required field", () => {
    const withoutTokens: Record<string, unknown> = { ...session };
    delete withoutTokens.total_tokens;
    expect(() => decodeSession(withoutTokens)).toThrow(FixtureDecodeError);
  });

  it("rejects a status outside the known set", () => {
    expect(() =>
      decodeSession({ ...session, status: "almost_done" })
    ).toThrow(/expected one of created/);
  });

  it("rejects an event category outside the closed set", () => {
    const drifted = {
      ...eventList,
      items: [{ ...eventList.items[0], category: "informational" }],
    };
    expect(() => decodeEventList(drifted)).toThrow(
      /expected one of system \| agent/
    );
  });

  it("rejects a wrongly typed counter", () => {
    expect(() =>
      decodeSession({ ...session, iteration_count: "two" })
    ).toThrow(/expected a number/);
  });
});

describe("type-level guarantees, enforced by tsc --noEmit", () => {
  type HasStringIndexSignature<T> = string extends keyof T ? true : false;
  type IsAny<T> = 0 extends 1 & T ? true : false;

  it("admits no arbitrary keys on the session or event payloads", () => {
    // An index signature here would let a component read a key the backend never
    // sends and get `undefined` instead of a compile error.
    expectTypeOf<HasStringIndexSignature<AgentSession>>().toEqualTypeOf<false>();
    expectTypeOf<HasStringIndexSignature<SessionEvent>>().toEqualTypeOf<false>();
    expectTypeOf<
      HasStringIndexSignature<SessionEventPayload>
    >().toEqualTypeOf<false>();

    const payload: SessionEventPayload = {};
    // @ts-expect-error the loop never emits this key, so reading it must not compile
    expect(payload.not_a_real_field).toBeUndefined();
  });

  it("types no contract as any", () => {
    expectTypeOf<IsAny<AgentSession>>().toEqualTypeOf<false>();
    expectTypeOf<IsAny<SessionEvent>>().toEqualTypeOf<false>();
    expectTypeOf<IsAny<SessionEventPayload>>().toEqualTypeOf<false>();
  });

  it("rejects a category outside the closed set", () => {
    // @ts-expect-error "informational" is not a SessionEventCategory
    const wrong: SessionEventCategory = "informational";
    expect(SESSION_EVENT_CATEGORIES).not.toContain(wrong);
  });
});
