# Generated by Django 6.0.7 on 2026-07-20 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_trip_distance_meters_trip_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('event_type', models.CharField(choices=[('pickup', 'Pickup'), ('drive', 'Drive'), ('break', 'Break'), ('fuel', 'Fuel Stop'), ('sleep', 'Sleep / Rest'), ('dropoff', 'Dropoff'), ('off_duty', 'Off Duty')], max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(help_text='Duration in hours')),
                ('distance', models.FloatField(default=0.0, help_text='Distance in miles')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trips.trip')),
            ],
            options={
                'ordering': ['trip', 'order'],
            },
        ),
    ]
