/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HosLogsRouteImport } from './routes/hos-logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RouteOptimizationRouteImport } from './routes/route-optimization'
import { Route as RoutePlannerRouteImport } from './routes/route-planner'
import { Route as TripsRouteImport } from './routes/trips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HosLogsRoute = HosLogsRouteImport.update({
  id: '/hos-logs',
  path: '/hos-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteOptimizationRoute = RouteOptimizationRouteImport.update({
  id: '/route-optimization',
  path: '/route-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutePlannerRoute = RoutePlannerRouteImport.update({
  id: '/route-planner',
  path: '/route-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hos-logs': typeof HosLogsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/route-optimization': typeof RouteOptimizationRoute
  '/route-planner': typeof RoutePlannerRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hos-logs': typeof HosLogsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/route-optimization': typeof RouteOptimizationRoute
  '/route-planner': typeof RoutePlannerRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hos-logs': typeof HosLogsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/route-optimization': typeof RouteOptimizationRoute
  '/route-planner': typeof RoutePlannerRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hos-logs'
    | '/login'
    | '/register'
    | '/route-optimization'
    | '/route-planner'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hos-logs'
    | '/login'
    | '/register'
    | '/route-optimization'
    | '/route-planner'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/hos-logs'
    | '/login'
    | '/register'
    | '/route-optimization'
    | '/route-planner'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HosLogsRoute: typeof HosLogsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RouteOptimizationRoute: typeof RouteOptimizationRoute
  RoutePlannerRoute: typeof RoutePlannerRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hos-logs': {
      id: '/hos-logs'
      path: '/hos-logs'
      fullPath: '/hos-logs'
      preLoaderRoute: typeof HosLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-optimization': {
      id: '/route-optimization'
      path: '/route-optimization'
      fullPath: '/route-optimization'
      preLoaderRoute: typeof RouteOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-planner': {
      id: '/route-planner'
      path: '/route-planner'
      fullPath: '/route-planner'
      preLoaderRoute: typeof RoutePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HosLogsRoute: HosLogsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RouteOptimizationRoute: RouteOptimizationRoute,
  RoutePlannerRoute: RoutePlannerRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
