ALTER TABLE assets
ADD COLUMN IF NOT EXISTS output_prefix TEXT,
ADD COLUMN IF NOT EXISTS master_playlist_key TEXT,
ADD COLUMN IF NOT EXISTS error_message TEXT,
ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
