export const PERMISSIONS = {
  // User management
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  // Inventory
  INVENTORY_CREATE: 'inventory:create',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_UPDATE: 'inventory:update',
  INVENTORY_DELETE: 'inventory:delete',
  // Attendance
  ATTENDANCE_CHECKIN: 'attendance:checkin',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_MANAGE: 'attendance:manage',
  // Customers
  CUSTOMER_CREATE: 'customer:create',
  CUSTOMER_READ: 'customer:read',
  CUSTOMER_UPDATE: 'customer:update',
  CUSTOMER_DELETE: 'customer:delete',
  // Reports
  REPORT_VIEW: 'report:view',
  REPORT_EXPORT: 'report:export',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  super_admin: Object.values(PERMISSIONS),
  admin: [
    PERMISSIONS.USER_CREATE, PERMISSIONS.USER_READ, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE, PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.CUSTOMER_CREATE, PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_UPDATE, PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT,
  ],
  manager: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.CUSTOMER_READ, PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.REPORT_VIEW,
  ],
  employee: [
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.CUSTOMER_READ,
  ],
};
