services:
  mongo:
    image: mongo:7
    container_name: nimbus-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garage
    volumes:
      - ./docker/garage/garage.toml:/etc/garage.toml
      - ./docker/garage/meta:/var/lib/garage/meta
      - ./docker/garage/data:/var/lib/garage/data
    restart: unless-stopped
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./docker/garage/garage.toml:/etc/garage.toml:ro
    ports:
      - "3909:3909"
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    depends_on:
      - garage

volumes:
  mongo_data:
  garage_meta:
  garage_data: