# 1. USER TABLE

type User @table(key: "clerkId") {
  clerkId: String! @unique
  email: String!
  username: String
  imageUrl: String
}

# 2. The Skill table

type Skill @table {
  id: UUID! @default(expr: "uuidV4()")

  # Relationship
  author: User!

  # SKill content

  title: String
  description: String
  tags: [String]!

  # Techincal

  installCommand: String!
  promptConfig: String!
  usageExample: String!

  # Metadata
  createdAt: Timestamp! @default(expr: "request.time")
}
