"""add_phase12_qa_tables

Revision ID: 425f80846725
Revises: ddf3db23c06d
Create Date: 2026-08-15 16:33:20.675053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '425f80846725'
down_revision: Union[str, Sequence[str], None] = 'ddf3db23c06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks_run', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_reports_generation_job_id'), 'qa_reports', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_qa_reports_passed'), 'qa_reports', ['passed'], unique=False)
    op.create_table('qa_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('qa_report_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('MEDIA', 'TIMELINE', 'AUDIO', 'CAPTIONS', 'ASSETS', 'STORY', 'VISUAL', name='qacategory'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='qaseverity'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('repairable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['qa_report_id'], ['qa_reports.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_issues_category'), 'qa_issues', ['category'], unique=False)
    op.create_index(op.f('ix_qa_issues_code'), 'qa_issues', ['code'], unique=False)
    op.create_index(op.f('ix_qa_issues_qa_report_id'), 'qa_issues', ['qa_report_id'], unique=False)
    op.create_index(op.f('ix_qa_issues_severity'), 'qa_issues', ['severity'], unique=False)
    op.create_table('repair_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=False),
    sa.Column('qa_report_id', sa.Uuid(), nullable=True),
    sa.Column('repair_type', sa.Enum('TIMELINE', 'ASSET', 'DIALOGUE', 'VOICE', 'CAPTION', 'AUDIO', 'SCENE', 'RENDER', name='repairtype'), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['qa_report_id'], ['qa_reports.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_attempts_generation_job_id'), 'repair_attempts', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_repair_attempts_repair_type'), 'repair_attempts', ['repair_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_repair_attempts_repair_type'), table_name='repair_attempts')
    op.drop_index(op.f('ix_repair_attempts_generation_job_id'), table_name='repair_attempts')
    op.drop_table('repair_attempts')
    op.drop_index(op.f('ix_qa_issues_severity'), table_name='qa_issues')
    op.drop_index(op.f('ix_qa_issues_qa_report_id'), table_name='qa_issues')
    op.drop_index(op.f('ix_qa_issues_code'), table_name='qa_issues')
    op.drop_index(op.f('ix_qa_issues_category'), table_name='qa_issues')
    op.drop_table('qa_issues')
    op.drop_index(op.f('ix_qa_reports_passed'), table_name='qa_reports')
    op.drop_index(op.f('ix_qa_reports_generation_job_id'), table_name='qa_reports')
    op.drop_table('qa_reports')
    # ### end Alembic commands ###
