"""add_phase11_voice_captions

Revision ID: ddf3db23c06d
Revises: 2ad0bcb2ef24
Create Date: 2026-08-15 15:52:18.767358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ddf3db23c06d'
down_revision: Union[str, Sequence[str], None] = '2ad0bcb2ef24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE assetpurpose ADD VALUE IF NOT EXISTS 'VOICE'")
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('voice_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_character_name'), 'voice_profiles', ['character_name'], unique=True)
    op.create_table('dialogue_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('character_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_segments_character_name'), 'dialogue_segments', ['character_name'], unique=False)
    op.create_index(op.f('ix_dialogue_segments_scene_id'), 'dialogue_segments', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_segments_scene_id'), table_name='dialogue_segments')
    op.drop_index(op.f('ix_dialogue_segments_character_name'), table_name='dialogue_segments')
    op.drop_table('dialogue_segments')
    op.drop_index(op.f('ix_voice_profiles_character_name'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    # ### end Alembic commands ###
