"""add timeline composition models

Revision ID: fded3b14a3b4
Revises: 9e3439b78937
Create Date: 2026-08-14 19:56:11.512389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fded3b14a3b4'
down_revision: Union[str, Sequence[str], None] = '9e3439b78937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captions_video_id'), 'captions', ['video_id'], unique=False)
    op.create_table('compositions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compositions_video_id'), 'compositions', ['video_id'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('track_type', sa.Enum('VIDEO', 'AUDIO', 'CAPTION', name='tracktype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_video_id'), 'tracks', ['video_id'], unique=False)
    op.create_table('scene_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('BACKGROUND', 'CHARACTER', 'PROP', 'AUDIO', 'MUSIC', 'VOICE', 'OVERLAY', name='sceneassetrole'), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_assets_asset_id'), 'scene_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scene_assets_scene_id'), 'scene_assets', ['scene_id'], unique=False)
    op.create_table('track_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_items_track_id'), 'track_items', ['track_id'], unique=False)
    transition_type_enum = sa.Enum('CUT', 'FADE', 'SLIDE', 'ZOOM', name='transitiontype')
    transition_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('scenes', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('scenes', sa.Column('start_ms', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('scenes', sa.Column('duration_ms', sa.Integer(), nullable=False, server_default='4000'))
    op.add_column('scenes', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scenes', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scenes', sa.Column('transition_in', transition_type_enum, nullable=False, server_default='CUT'))
    op.create_index(op.f('ix_scenes_order'), 'scenes', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_order'), table_name='scenes')
    op.drop_column('scenes', 'transition_in')
    op.drop_column('scenes', 'description')
    op.drop_column('scenes', 'title')
    op.drop_column('scenes', 'duration_ms')
    op.drop_column('scenes', 'start_ms')
    op.drop_column('scenes', 'order')
    op.drop_index(op.f('ix_track_items_track_id'), table_name='track_items')
    op.drop_table('track_items')
    op.drop_index(op.f('ix_scene_assets_scene_id'), table_name='scene_assets')
    op.drop_index(op.f('ix_scene_assets_asset_id'), table_name='scene_assets')
    op.drop_table('scene_assets')
    op.drop_index(op.f('ix_tracks_video_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_compositions_video_id'), table_name='compositions')
    op.drop_table('compositions')
    op.drop_index(op.f('ix_captions_video_id'), table_name='captions')
    op.drop_table('captions')
    # ### end Alembic commands ###
