import { SchemaAST, LogicalColumnType } from "../ast/types.js";

function mapDrizzleFunc(type: LogicalColumnType): string {
  switch (type) {
    case "Integer": return "integer";
    case "String": return "varchar";
    case "Boolean": return "boolean";
    case "Float": return "real";
    case "Decimal": return "decimal";
    case "Date": return "date";
    case "Timestamp": return "timestamp";
    case "UUID": return "uuid";
    case "JSON": return "jsonb";
    default: return "varchar";
  }
}

export function generateDrizzle(ast: SchemaAST): string {
  let code = `import { pgTable, serial, integer, varchar, boolean, real, decimal, date, timestamp, uuid, jsonb } from "drizzle-orm/pg-core";\n`;
  code += `// Drizzle ORM Schema generated by Schema Engine\n// Generated at: ${new Date().toISOString()}\n\n`;

  for (const table of ast.tables) {
    const tableName = table.name.toLowerCase().replace(/[^a-z0-9_]+/g, "_");
    code += `export const ${tableName} = pgTable("${tableName}", {\n`;

    for (const col of table.columns) {
      const colName = col.name.toLowerCase().replace(/[^a-z0-9_]+/g, "_");
      let typeCall = "";

      if (col.autoIncrement && col.primaryKey && col.type === "Integer") {
        typeCall = `serial("${colName}")`;
      } else {
        const creatorFunc = mapDrizzleFunc(col.type);
        typeCall = `${creatorFunc}("${colName}"`;
        if (col.type === "String") {
          typeCall += `, { length: 255 }`;
        }
        typeCall += `)`;
      }

      let chain = "";
      if (col.primaryKey && !typeCall.startsWith("serial")) {
        chain += `.primaryKey()`;
      }
      if (!col.nullable) {
        chain += `.notNull()`;
      }
      if (col.unique) {
        chain += `.unique()`;
      }
      if (col.defaultValue !== undefined && col.defaultValue.trim() !== "") {
        const val = col.defaultValue.trim();
        const isString = ["String", "Date", "Timestamp", "UUID"].includes(col.type);
        if (isString && !val.startsWith("'")) {
          chain += `.default('${val}')`;
        } else {
          chain += `.default(${val})`;
        }
      }

      // References
      const rel = ast.relationships.find((r) => r.sourceTable === table.name && r.sourceColumn === col.name);
      if (rel) {
        chain += `.references(() => ${rel.targetTable}.${rel.targetColumn})`;
      }

      code += `  ${col.name}: ${typeCall}${chain},\n`;
    }

    code += `});\n\n`;
  }

  return code;
}
