import { SchemaAST, LogicalColumnType } from "../ast/types.js";

function mapMongooseType(type: LogicalColumnType): string {
  switch (type) {
    case "Integer": return "Number";
    case "String": return "String";
    case "Boolean": return "Boolean";
    case "Float": return "Number";
    case "Decimal": return "Number";
    case "Date": return "Date";
    case "Timestamp": return "Date";
    case "UUID": return "mongoose.Schema.Types.ObjectId";
    case "JSON": return "mongoose.Schema.Types.Mixed";
    default: return "String";
  }
}

export function generateMongoose(ast: SchemaAST): string {
  let code = `import mongoose from "mongoose";\n`;
  code += `// Mongoose Schemas generated by Schema Engine\n// Generated at: ${new Date().toISOString()}\n\n`;

  for (const table of ast.tables) {
    const className = table.name.charAt(0).toUpperCase() + table.name.slice(1);
    code += `const ${className}Schema = new mongoose.Schema({\n`;

    for (const col of table.columns) {
      if (col.name === "_id" || col.name === "id") continue; // Mongoose creates _id automatically

      const mType = mapMongooseType(col.type);
      const options: string[] = [];
      options.push(`type: ${mType}`);
      if (!col.nullable) options.push("required: true");
      if (col.unique) options.push("unique: true");
      if (col.defaultValue !== undefined && col.defaultValue.trim() !== "") {
        const val = col.defaultValue.trim();
        const isStr = ["String", "Date", "Timestamp", "UUID"].includes(col.type);
        if (isStr && !val.startsWith("'")) {
          options.push(`default: "${val}"`);
        } else {
          options.push(`default: ${val}`);
        }
      }

      // Check for reference
      const rel = ast.relationships.find((r) => r.sourceTable === table.name && r.sourceColumn === col.name);
      if (rel) {
        const refName = rel.targetTable.charAt(0).toUpperCase() + rel.targetTable.slice(1);
        options.push(`ref: "${refName}"`);
      }

      code += `  ${col.name}: { ${options.join(", ")} },\n`;
    }

    code += `});\n\n`;
    code += `export const ${className} = mongoose.models.${className} || mongoose.model("${className}", ${className}Schema);\n\n`;
  }

  return code;
}
