import { SchemaAST, LogicalColumnType } from "../ast/types.js";

function mapPrismaType(type: LogicalColumnType): string {
  switch (type) {
    case "Integer": return "Int";
    case "String": return "String";
    case "Boolean": return "Boolean";
    case "Float": return "Float";
    case "Decimal": return "Decimal";
    case "Date": return "DateTime";
    case "Timestamp": return "DateTime";
    case "UUID": return "String"; // String with @default(uuid())
    case "JSON": return "Json";
    default: return "String";
  }
}

export function generatePrisma(ast: SchemaAST): string {
  let schema = `// Prisma Schema file generated by Schema Engine\n// Generated at: ${new Date().toISOString()}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\n`;

  for (const table of ast.tables) {
    const modelName = table.name.charAt(0).toUpperCase() + table.name.slice(1);
    schema += `model ${modelName} {\n`;

    // Process columns
    for (const col of table.columns) {
      let typeStr = mapPrismaType(col.type);
      if (col.nullable) {
        typeStr += "?";
      }

      let attributes = "";
      if (col.primaryKey) {
        attributes += " @id";
      }
      if (col.unique) {
        attributes += " @unique";
      }
      if (col.autoIncrement) {
        attributes += " @default(autoincrement())";
      } else if (col.type === "UUID" && col.primaryKey) {
        attributes += " @default(uuid())";
      } else if (col.defaultValue !== undefined && col.defaultValue.trim() !== "") {
        const val = col.defaultValue.trim();
        attributes += ` @default(${val})`;
      }

      // Check for inline relationship foreign key mapping
      const relation = ast.relationships.find(
        (r) => r.sourceTable === table.name && r.sourceColumn === col.name
      );
      if (relation) {
        const targetModel = relation.targetTable.charAt(0).toUpperCase() + relation.targetTable.slice(1);
        attributes += ` @relation(fields: [${col.name}], references: [${relation.targetColumn}])`;
      }

      schema += `  ${col.name} ${typeStr}${attributes}\n`;
    }

    // Process potential back-relations for prisma
    const backRelations = ast.relationships.filter((r) => r.targetTable === table.name);
    for (const rel of backRelations) {
      const sourceModel = rel.sourceTable.charAt(0).toUpperCase() + rel.sourceTable.slice(1);
      schema += `  ${rel.sourceTable}s ${sourceModel}[]\n`;
    }

    schema += `}\n\n`;
  }

  return schema;
}
