import { SchemaAST, LogicalColumnType } from "../ast/types.js";

function mapTypeormColumnType(type: LogicalColumnType): string {
  switch (type) {
    case "Integer": return "int";
    case "String": return "varchar";
    case "Boolean": return "boolean";
    case "Float": return "float";
    case "Decimal": return "decimal";
    case "Date": return "date";
    case "Timestamp": return "timestamp";
    case "UUID": return "uuid";
    case "JSON": return "jsonb";
    default: return "varchar";
  }
}

function mapTypeormTsType(type: LogicalColumnType): string {
  switch (type) {
    case "Integer": return "number";
    case "String": return "string";
    case "Boolean": return "boolean";
    case "Float": return "number";
    case "Decimal": return "number";
    case "Date": return "Date";
    case "Timestamp": return "Date";
    case "UUID": return "string";
    case "JSON": return "any";
    default: return "string";
  }
}

export function generateTypeorm(ast: SchemaAST): string {
  let code = `import { Entity, Column, PrimaryColumn, PrimaryGeneratedColumn, ManyToOne, OneToMany, JoinColumn } from "typeorm";\n`;
  code += `// TypeORM Entity declarations generated by Schema Engine\n// Generated at: ${new Date().toISOString()}\n\n`;

  for (const table of ast.tables) {
    const className = table.name.charAt(0).toUpperCase() + table.name.slice(1);
    code += `@Entity("${table.name}")\nexport class ${className} {\n`;

    for (const col of table.columns) {
      const tsType = mapTypeormTsType(col.type);
      const ormType = mapTypeormColumnType(col.type);

      if (col.primaryKey) {
        if (col.autoIncrement) {
          code += `  @PrimaryGeneratedColumn()\n  ${col.name}: ${tsType};\n\n`;
        } else {
          code += `  @PrimaryColumn({ type: "${ormType}" })\n  ${col.name}: ${tsType};\n\n`;
        }
      } else {
        const options: string[] = [];
        options.push(`type: "${ormType}"`);
        if (col.nullable) options.push("nullable: true");
        if (col.unique) options.push("unique: true");
        if (col.defaultValue !== undefined && col.defaultValue.trim() !== "") {
          const val = col.defaultValue.trim();
          if (["String", "Date", "Timestamp", "UUID"].includes(col.type) && !val.startsWith("'")) {
            options.push(`default: "${val}"`);
          } else {
            options.push(`default: ${val}`);
          }
        }

        code += `  @Column({ ${options.join(", ")} })\n  ${col.name}: ${tsType};\n\n`;
      }
    }

    // Process relationships
    const rels = ast.relationships.filter((r) => r.sourceTable === table.name);
    for (const rel of rels) {
      const targetClass = rel.targetTable.charAt(0).toUpperCase() + rel.targetTable.slice(1);
      code += `  @ManyToOne(() => ${targetClass})\n  @JoinColumn({ name: "${rel.sourceColumn}" })\n  ${rel.sourceTable}: ${targetClass};\n\n`;
    }

    code += `}\n\n`;
  }

  return code;
}
