"""agent_sessions_and_events

Creates the two tables that make an agent execution durable: ``agent_sessions``
for the session itself and ``agent_session_events`` for its chronological event
feed.

Both tables are purely additive. No existing table is altered, no existing row is
rewritten, and ``runs`` / ``run_steps`` are untouched, so no agent run history is
lost. Rollback is a plain drop of the two new tables.

``agent_sessions.id`` is the human-readable ``sess_<hex>`` string the agent loop
already generates, so it is the primary key directly and persisting a session
needs no identifier remapping. ``steps`` is a JSON column rather than a third
table: loop steps are heterogeneous, are only ever read as an ordered whole, and
are never queried by field. Holding them in the session row also makes each
persist atomic, so status, counters, and steps cannot disagree.

``ix_agent_session_events_session_id_sequence`` exists to serve the event feed
directly, which filters by session and orders by sequence.

Revision ID: ba25c798a0aa
Revises: b7e2c4a91d38
Create Date: 2026-09-26 11:18:46.528097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba25c798a0aa'
down_revision: Union[str, Sequence[str], None] = 'b7e2c4a91d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('task_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('executed_action_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('completed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('termination_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_owner_id'), 'agent_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_repository_id'), 'agent_sessions', ['repository_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.create_table('agent_session_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_session_events_category'), 'agent_session_events', ['category'], unique=False)
    op.create_index(op.f('ix_agent_session_events_event_type'), 'agent_session_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_session_events_id'), 'agent_session_events', ['id'], unique=False)
    op.create_index(op.f('ix_agent_session_events_session_id'), 'agent_session_events', ['session_id'], unique=False)
    op.create_index('ix_agent_session_events_session_id_sequence', 'agent_session_events', ['session_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_session_events_session_id_sequence', table_name='agent_session_events')
    op.drop_index(op.f('ix_agent_session_events_session_id'), table_name='agent_session_events')
    op.drop_index(op.f('ix_agent_session_events_id'), table_name='agent_session_events')
    op.drop_index(op.f('ix_agent_session_events_event_type'), table_name='agent_session_events')
    op.drop_index(op.f('ix_agent_session_events_category'), table_name='agent_session_events')
    op.drop_table('agent_session_events')
    op.drop_index(op.f('ix_agent_sessions_status'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_repository_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_owner_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
