# Generated by Django 6.0.7 on 2026-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_current_lat_trip_current_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_geometry',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
