# Generated by Django 6.0.7 on 2026-07-20 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0003_trip_distance_meters_trip_duration_seconds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Fuel", "Fuel"),
                            ("Truck Stop", "Truck Stop"),
                            ("Rest Area", "Rest Area"),
                            ("Parking", "Parking"),
                            ("Hotel", "Hotel"),
                            ("Food", "Food"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Truck Stop",
                        max_length=50,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "distance_from_start",
                    models.FloatField(
                        default=0.0, help_text="Distance from route origin in miles"
                    ),
                ),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.FloatField(default=0.5, help_text="Stop duration in hours"),
                ),
                (
                    "priority",
                    models.FloatField(
                        default=5.0, help_text="Scoring priority out of 100"
                    ),
                ),
                ("source", models.CharField(default="OpenStreetMap", max_length=100)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_custom", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "distance_from_start"],
            },
        ),
    ]
