import type { Permission, Role } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  OWNER: [
    "dashboard.view",
    "employees.view",
    "employees.manage",
    "attendance.view",
    "attendance.manage",
    "payroll.view",
    "payroll.manage",
    "finance.view",
    "finance.manage",
    "inventory.view",
    "inventory.manage",
    "pos.view",
    "pos.create",
    "services.view",
    "services.manage",
    "reports.view",
    "notifications.view",
    "settings.manage",
  ],
  MANAGER: [
    "dashboard.view",
    "employees.view",
    "employees.manage",
    "attendance.view",
    "attendance.manage",
    "payroll.view",
    "inventory.view",
    "inventory.manage",
    "pos.view",
    "pos.create",
    "services.view",
    "services.manage",
    "reports.view",
    "notifications.view",
  ],
  RECEPTIONIST: [
    "dashboard.view",
    "attendance.view",
    "inventory.view",
    "pos.view",
    "pos.create",
    "services.view",
    "notifications.view",
  ],
  BARBER: [
    "dashboard.view",
    "attendance.view",
    "services.view",
    "notifications.view",
  ],
};
