// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAssetProcessing = `-- name: ClaimAssetProcessing :one
UPDATE assets
SET
    processing_attempts = processing_attempts + 1,
    last_started_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, object_key, original_filename, content_type, size_bytes, status, created_at, updated_at, output_prefix, master_playlist_key, error_message, processed_at, processing_attempts, last_started_at, failed_at, mime_type, original_key, hls_manifest_key, duration_seconds, processing_started_at, processing_completed_at
`

func (q *Queries) ClaimAssetProcessing(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, claimAssetProcessing, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputPrefix,
		&i.MasterPlaylistKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.ProcessingAttempts,
		&i.LastStartedAt,
		&i.FailedAt,
		&i.MimeType,
		&i.OriginalKey,
		&i.HlsManifestKey,
		&i.DurationSeconds,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
	)
	return i, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    id,
    object_key,
    original_filename,
    content_type,
    size_bytes,
    status
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, object_key, original_filename, content_type, size_bytes, status, created_at, updated_at, output_prefix, master_playlist_key, error_message, processed_at, processing_attempts, last_started_at, failed_at, mime_type, original_key, hls_manifest_key, duration_seconds, processing_started_at, processing_completed_at
`

type CreateAssetParams struct {
	ID               pgtype.UUID `json:"id"`
	ObjectKey        string      `json:"object_key"`
	OriginalFilename pgtype.Text `json:"original_filename"`
	ContentType      string      `json:"content_type"`
	SizeBytes        pgtype.Int8 `json:"size_bytes"`
	Status           string      `json:"status"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputPrefix,
		&i.MasterPlaylistKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.ProcessingAttempts,
		&i.LastStartedAt,
		&i.FailedAt,
		&i.MimeType,
		&i.OriginalKey,
		&i.HlsManifestKey,
		&i.DurationSeconds,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, object_key, original_filename, content_type, size_bytes, status, created_at, updated_at, output_prefix, master_playlist_key, error_message, processed_at, processing_attempts, last_started_at, failed_at, mime_type, original_key, hls_manifest_key, duration_seconds, processing_started_at, processing_completed_at FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputPrefix,
		&i.MasterPlaylistKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.ProcessingAttempts,
		&i.LastStartedAt,
		&i.FailedAt,
		&i.MimeType,
		&i.OriginalKey,
		&i.HlsManifestKey,
		&i.DurationSeconds,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
	)
	return i, err
}

const updateAssetCompletion = `-- name: UpdateAssetCompletion :one
UPDATE assets
SET
    status = $2,
    output_prefix = $3,
    master_playlist_key = $4,
    processed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, object_key, original_filename, content_type, size_bytes, status, created_at, updated_at, output_prefix, master_playlist_key, error_message, processed_at, processing_attempts, last_started_at, failed_at, mime_type, original_key, hls_manifest_key, duration_seconds, processing_started_at, processing_completed_at
`

type UpdateAssetCompletionParams struct {
	ID                pgtype.UUID `json:"id"`
	Status            string      `json:"status"`
	OutputPrefix      pgtype.Text `json:"output_prefix"`
	MasterPlaylistKey pgtype.Text `json:"master_playlist_key"`
}

func (q *Queries) UpdateAssetCompletion(ctx context.Context, arg UpdateAssetCompletionParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetCompletion,
		arg.ID,
		arg.Status,
		arg.OutputPrefix,
		arg.MasterPlaylistKey,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputPrefix,
		&i.MasterPlaylistKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.ProcessingAttempts,
		&i.LastStartedAt,
		&i.FailedAt,
		&i.MimeType,
		&i.OriginalKey,
		&i.HlsManifestKey,
		&i.DurationSeconds,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
	)
	return i, err
}

const updateAssetFailure = `-- name: UpdateAssetFailure :one
UPDATE assets
SET
    status = 'failed',
    failed_at = NOW(),
    error_message = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, object_key, original_filename, content_type, size_bytes, status, created_at, updated_at, output_prefix, master_playlist_key, error_message, processed_at, processing_attempts, last_started_at, failed_at, mime_type, original_key, hls_manifest_key, duration_seconds, processing_started_at, processing_completed_at
`

type UpdateAssetFailureParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateAssetFailure(ctx context.Context, arg UpdateAssetFailureParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetFailure, arg.ID, arg.ErrorMessage)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputPrefix,
		&i.MasterPlaylistKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.ProcessingAttempts,
		&i.LastStartedAt,
		&i.FailedAt,
		&i.MimeType,
		&i.OriginalKey,
		&i.HlsManifestKey,
		&i.DurationSeconds,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
	)
	return i, err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :one
UPDATE assets
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, object_key, original_filename, content_type, size_bytes, status, created_at, updated_at, output_prefix, master_playlist_key, error_message, processed_at, processing_attempts, last_started_at, failed_at, mime_type, original_key, hls_manifest_key, duration_seconds, processing_started_at, processing_completed_at
`

type UpdateAssetStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetStatus, arg.ID, arg.Status)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputPrefix,
		&i.MasterPlaylistKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.ProcessingAttempts,
		&i.LastStartedAt,
		&i.FailedAt,
		&i.MimeType,
		&i.OriginalKey,
		&i.HlsManifestKey,
		&i.DurationSeconds,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
	)
	return i, err
}
