// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    tenant_id,
    created_by,
    title,
    slug,
    description
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, created_by, title, slug, description, status, created_at, updated_at
`

type CreateCourseParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.TenantID,
		arg.CreatedBy,
		arg.Title,
		arg.Slug,
		arg.Description,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = $1 AND tenant_id = $2
`

type DeleteCourseParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCourse(ctx context.Context, arg DeleteCourseParams) error {
	_, err := q.db.Exec(ctx, deleteCourse, arg.ID, arg.TenantID)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT
    id,
    tenant_id,
    title,
    description,
    status
FROM courses
WHERE id = $1
  AND tenant_id = $2
`

type GetCourseParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetCourseRow struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) GetCourse(ctx context.Context, arg GetCourseParams) (GetCourseRow, error) {
	row := q.db.QueryRow(ctx, getCourse, arg.ID, arg.TenantID)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const getCourseByIDAndTenant = `-- name: GetCourseByIDAndTenant :one
SELECT id, tenant_id, created_by, title, slug, description, status, created_at, updated_at FROM courses
WHERE id = $1 AND tenant_id = $2
`

type GetCourseByIDAndTenantParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCourseByIDAndTenant(ctx context.Context, arg GetCourseByIDAndTenantParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByIDAndTenant, arg.ID, arg.TenantID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoursesByTenant = `-- name: ListCoursesByTenant :many
SELECT id, tenant_id, created_by, title, slug, description, status, created_at, updated_at FROM courses
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCoursesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CreatedBy,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCoursesByTenantID = `-- name: ListPublishedCoursesByTenantID :many
SELECT
    id,
    title,
    description
FROM courses
WHERE tenant_id = $1
  AND status = 'published'
ORDER BY created_at DESC
`

type ListPublishedCoursesByTenantIDRow struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
}

func (q *Queries) ListPublishedCoursesByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]ListPublishedCoursesByTenantIDRow, error) {
	rows, err := q.db.Query(ctx, listPublishedCoursesByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedCoursesByTenantIDRow{}
	for rows.Next() {
		var i ListPublishedCoursesByTenantIDRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses
SET
    title = $1,
    slug = $2,
    description = $3,
    updated_at = NOW()
WHERE id = $4 AND tenant_id = $5
`

type UpdateCourseParams struct {
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.Exec(ctx, updateCourse,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ID,
		arg.TenantID,
	)
	return err
}
