// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (
    id,
    tenant_id,
    user_id,
    course_id
)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, course_id, created_at
`

type CreateEnrollmentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	CourseID pgtype.UUID `json:"course_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.CourseID,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, tenant_id, user_id, course_id, created_at FROM enrollments
WHERE tenant_id = $1 AND user_id = $2 AND course_id = $3
`

type GetEnrollmentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	CourseID pgtype.UUID `json:"course_id"`
}

func (q *Queries) GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, arg.TenantID, arg.UserID, arg.CourseID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.CreatedAt,
	)
	return i, err
}

const listUserEnrollments = `-- name: ListUserEnrollments :many
SELECT id, tenant_id, user_id, course_id, created_at FROM enrollments
WHERE tenant_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListUserEnrollmentsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListUserEnrollments(ctx context.Context, arg ListUserEnrollmentsParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listUserEnrollments, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CourseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
