// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson_progress.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT id, tenant_id, user_id, lesson_id, position_seconds, completed_at, updated_at FROM lesson_progress
WHERE tenant_id = $1
  AND user_id = $2
  AND lesson_id = $3
`

type GetLessonProgressParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	LessonID pgtype.UUID `json:"lesson_id"`
}

func (q *Queries) GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, getLessonProgress, arg.TenantID, arg.UserID, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.LessonID,
		&i.PositionSeconds,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLessonProgressForUser = `-- name: ListLessonProgressForUser :many
SELECT id, tenant_id, user_id, lesson_id, position_seconds, completed_at, updated_at FROM lesson_progress
WHERE tenant_id = $1
  AND user_id = $2
`

type ListLessonProgressForUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListLessonProgressForUser(ctx context.Context, arg ListLessonProgressForUserParams) ([]LessonProgress, error) {
	rows, err := q.db.Query(ctx, listLessonProgressForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonProgress{}
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.LessonID,
			&i.PositionSeconds,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO lesson_progress (
    id,
    tenant_id,
    user_id,
    lesson_id,
    position_seconds,
    completed_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (tenant_id, user_id, lesson_id)
DO UPDATE SET
    position_seconds = EXCLUDED.position_seconds,
    completed_at = COALESCE(EXCLUDED.completed_at, lesson_progress.completed_at),
    updated_at = NOW()
RETURNING id, tenant_id, user_id, lesson_id, position_seconds, completed_at, updated_at
`

type UpsertLessonProgressParams struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	LessonID        pgtype.UUID        `json:"lesson_id"`
	PositionSeconds int32              `json:"position_seconds"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.LessonID,
		arg.PositionSeconds,
		arg.CompletedAt,
	)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.LessonID,
		&i.PositionSeconds,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
