// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO tenant_members (
    tenant_id,
    user_id,
    role
)
VALUES ($1, $2, $3)
`

type CreateMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     string      `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT tenant_id, user_id, role, created_at
FROM tenant_members
WHERE user_id = $1 AND tenant_id = $2
`

type GetMembershipParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetMembershipRow struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.TenantID)
	var i GetMembershipRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT tenant_id, user_id, role, created_at
FROM tenant_members
WHERE user_id = $1
`

type ListUserMembershipsRow struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUserMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMembershipsRow{}
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMembershipsWithDetails = `-- name: ListUserMembershipsWithDetails :many
SELECT
    t.id AS tenant_id,
    t.name AS tenant_name,
    t.slug AS tenant_slug,
    tm.role AS role
FROM tenant_members tm
JOIN tenants t ON tm.tenant_id = t.id
WHERE tm.user_id = $1
ORDER BY t.name ASC
`

type ListUserMembershipsWithDetailsRow struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	TenantName string      `json:"tenant_name"`
	TenantSlug string      `json:"tenant_slug"`
	Role       string      `json:"role"`
}

func (q *Queries) ListUserMembershipsWithDetails(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listUserMembershipsWithDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMembershipsWithDetailsRow{}
	for rows.Next() {
		var i ListUserMembershipsWithDetailsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.TenantSlug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
