// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID                    pgtype.UUID        `json:"id"`
	ObjectKey             string             `json:"object_key"`
	OriginalFilename      pgtype.Text        `json:"original_filename"`
	ContentType           string             `json:"content_type"`
	SizeBytes             pgtype.Int8        `json:"size_bytes"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	OutputPrefix          pgtype.Text        `json:"output_prefix"`
	MasterPlaylistKey     pgtype.Text        `json:"master_playlist_key"`
	ErrorMessage          pgtype.Text        `json:"error_message"`
	ProcessedAt           pgtype.Timestamptz `json:"processed_at"`
	ProcessingAttempts    int32              `json:"processing_attempts"`
	LastStartedAt         pgtype.Timestamptz `json:"last_started_at"`
	FailedAt              pgtype.Timestamptz `json:"failed_at"`
	MimeType              pgtype.Text        `json:"mime_type"`
	OriginalKey           pgtype.Text        `json:"original_key"`
	HlsManifestKey        pgtype.Text        `json:"hls_manifest_key"`
	DurationSeconds       pgtype.Int4        `json:"duration_seconds"`
	ProcessingStartedAt   pgtype.Timestamptz `json:"processing_started_at"`
	ProcessingCompletedAt pgtype.Timestamptz `json:"processing_completed_at"`
}

type Course struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CourseSection struct {
	ID        pgtype.UUID        `json:"id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	Title     string             `json:"title"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Enrollment struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Lesson struct {
	ID           pgtype.UUID        `json:"id"`
	CourseID     pgtype.UUID        `json:"course_id"`
	SectionID    pgtype.UUID        `json:"section_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Position     int32              `json:"position"`
	ContentType  string             `json:"content_type"`
	VideoAssetID pgtype.UUID        `json:"video_asset_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LessonProgress struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	LessonID        pgtype.UUID        `json:"lesson_id"`
	PositionSeconds int32              `json:"position_seconds"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Membership struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	TokenHash  []byte             `json:"token_hash"`
}

type Tenant struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Description    string             `json:"description"`
	LogoUrl        string             `json:"logo_url"`
	FaviconUrl     string             `json:"favicon_url"`
	PrimaryColor   string             `json:"primary_color"`
	SecondaryColor string             `json:"secondary_color"`
	CustomDomain   string             `json:"custom_domain"`
}

type TenantMember struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ID        pgtype.UUID        `json:"id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
