// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimAssetProcessing(ctx context.Context, id pgtype.UUID) (Asset, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionWithTokenHash(ctx context.Context, arg CreateSessionWithTokenHashParams) (Session, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCourse(ctx context.Context, arg DeleteCourseParams) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error)
	GetCourse(ctx context.Context, arg GetCourseParams) (GetCourseRow, error)
	GetCourseByIDAndTenant(ctx context.Context, arg GetCourseByIDAndTenantParams) (Course, error)
	GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (Enrollment, error)
	GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (LessonProgress, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCoursesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Course, error)
	ListLessonProgressForUser(ctx context.Context, arg ListLessonProgressForUserParams) ([]LessonProgress, error)
	ListPublishedCoursesByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]ListPublishedCoursesByTenantIDRow, error)
	ListUserEnrollments(ctx context.Context, arg ListUserEnrollmentsParams) ([]Enrollment, error)
	ListUserMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsRow, error)
	ListUserMembershipsWithDetails(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsWithDetailsRow, error)
	UpdateAssetCompletion(ctx context.Context, arg UpdateAssetCompletionParams) (Asset, error)
	UpdateAssetFailure(ctx context.Context, arg UpdateAssetFailureParams) (Asset, error)
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Asset, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) error
	UpdateSessionLastUsed(ctx context.Context, id pgtype.UUID) error
	UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (LessonProgress, error)
}

var _ Querier = (*Queries)(nil)
