CREATE TABLE users (
	id TEXT PRIMARY KEY,
	email TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	token TEXT UNIQUE NOT NULL,
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servers (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	ip TEXT NOT NULL,
	os TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT 'offline',
	cpu_usage DOUBLE PRECISION NOT NULL DEFAULT 0,
	memory_usage DOUBLE PRECISION NOT NULL DEFAULT 0,
	memory_total DOUBLE PRECISION NOT NULL DEFAULT 0,
	disk_usage DOUBLE PRECISION NOT NULL DEFAULT 0,
	disk_total DOUBLE PRECISION NOT NULL DEFAULT 0,
	network_in DOUBLE PRECISION NOT NULL DEFAULT 0,
	network_out DOUBLE PRECISION NOT NULL DEFAULT 0,
	uptime BIGINT NOT NULL DEFAULT 0,
	location TEXT NOT NULL DEFAULT '',
	provider TEXT NOT NULL DEFAULT '',
	tags TEXT NOT NULL DEFAULT '',
	ssh_port INTEGER NOT NULL DEFAULT 22,
	ssh_user TEXT NOT NULL DEFAULT 'root',
	ssh_auth_method TEXT NOT NULL DEFAULT 'password',
	ssh_password TEXT NOT NULL DEFAULT '',
	ssh_private_key TEXT NOT NULL DEFAULT '',
	ssh_passphrase TEXT NOT NULL DEFAULT '',
	host_key TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE monitoring_snapshots (
	id TEXT PRIMARY KEY,
	server_id TEXT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
	cpu_usage DOUBLE PRECISION NOT NULL,
	memory_usage DOUBLE PRECISION NOT NULL,
	disk_usage DOUBLE PRECISION NOT NULL,
	network_in DOUBLE PRECISION NOT NULL,
	network_out DOUBLE PRECISION NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activities (
	id TEXT PRIMARY KEY,
	message TEXT NOT NULL,
	type TEXT NOT NULL,
	"user" TEXT NOT NULL,
	server_id TEXT,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
	id TEXT PRIMARY KEY,
	title TEXT NOT NULL,
	message TEXT NOT NULL,
	type TEXT NOT NULL,
	read BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
